Gabi/InstitutoCurso/ASP .NET MVC/Models/Curso.cs
using System.ComponentModel.DataAnnotations;

namespace ASP_.NET_MVC.Models
{
    public class Curso
    {
        [Key]
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public DateTime FechaInicio { get; set; }
        public DateTime FechaFin { get; set; }
        public bool Disponible { get; set; }
    }
}

Gabi/InstitutoCurso/ASP .NET MVC/Models/Error.cs
namespace ASP_.NET_MVC.Models
{
    public class Error
    {
    }
}

Gabi/InstitutoCurso/ASP .NET MVC/Models/ErrorViewModel.cs
namespace ASP_.NET_MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Gabi/InstitutoCurso/ASP .NET MVC/Models/Institucion.cs
using System.ComponentModel.DataAnnotations;

namespace ASP_.NET_MVC.Models
{
    public class Institucion
    {
        [Key]
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
    }
}

Gabi/InstitutoCurso/ASP .NET MVC/Models/Usuario.cs
using System.ComponentModel.DataAnnotations;

namespace ASP_.NET_MVC.Models
{
    public class Usuario
    {
        [Key]
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
    }
}

Gabi/InstitutoCurso/ASP .NET MVC/Controllers/CursosController.cs
using ASP_.NET_MVC.Data;
using ASP_.NET_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using EntityState = Microsoft.EntityFrameworkCore.EntityState;


namespace ASP_.NET_MVC.Controllers
{
    public class CursosController : Controller
    {
        private readonly InstitutoDbContext _context;

        public CursosController(InstitutoDbContext context)
        {
            _context = context;
        }

        // Acción para registrar un nuevo curso
        [HttpGet]
        public ActionResult RegistroCursos()
        {
            return View();
        }

        [HttpPost]
        public ActionResult RegistroCursos(Curso curso)
        {
            if (ModelState.IsValid)
            {
                // Guardar el nuevo usuario en la base de datos
                _context.Cursos.Add(curso);
                _context.SaveChanges();
                TempData["Mensaje"] = "Curso registrado exitosamente";

                // Redirigir a la página de inicio de sesión o a otra vista según tus necesidades
                return RedirectToAction("Index", "Home");
            }

            return View(curso);
        }


        // Acción para mostrar los cursos disponibles
        public ActionResult Index()
        {
            var cursos = _context.Cursos.Where(c => c.Disponible).ToList();
            return View(cursos);
        }

        // Acción para ver detalles de un curso específico
        public ActionResult Detalles(int id)
        {
            Curso curso = _context.Cursos.Find(id);
            if (curso == null)
            {
                return RedirectToAction("Error404", "Error");
            }

            return View(curso);
        }
    }
}

Gabi/InstitutoCurso/ASP .NET MVC/Controllers/HomeController.cs
using ASP_.NET_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ASP_.NET_MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Gabi/InstitutoCurso/ASP .NET MVC/Controllers/InstitucionController.cs
using ASP_.NET_MVC.Data;
using ASP_.NET_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using EntityState = Microsoft.EntityFrameworkCore.EntityState;

namespace ASP_.NET_MVC.Controllers
{
    public class InstitucionController : Controller
    {
        private readonly InstitutoDbContext _context;

        public InstitucionController(InstitutoDbContext context)
        {
            _context = context;
        }

        // Acción para registrar una nueva institucion
        [HttpGet]
        public ActionResult RegistroInstitucion()
        {
            return View();
        }

        [HttpPost]
        public ActionResult RegistroInstitucion(Institucion institucion)
        {
            if (ModelState.IsValid)
            {
                // Guardar el nuevo usuario en la base de datos
                _context.Instituciones.Add(institucion);
                _context.SaveChanges();
                TempData["Mensaje"] = "Institucion registrada exitosamente";

                // Redirigir a la página de inicio de sesión o a otra vista según tus necesidades
                return RedirectToAction("Index", "Home");
            }

            return View(institucion);
        }

        // Acción para mostrar la descripción de la institución y los cursos ofrecidos
        public ActionResult Index()
        {
            var institucion = _context.Instituciones.FirstOrDefault();
            if (institucion == null)
            {
                return RedirectToAction("Error404", "Error");
            }

            return View(institucion);
        }

        // Acción para actualizar los cursos ofrecidos
        [HttpGet]
        public ActionResult ActualizarCursos(int id)
        {
            Institucion institucion = _context.Instituciones.Find(id);
            if (institucion == null)
            {
                return RedirectToAction("Error404", "Error");
            }

            return View(institucion);
        }

        [HttpPost]
        public ActionResult ActualizarCursos(Institucion institucion)
        {
            if (ModelState.IsValid)
            {
                _context.Entry(institucion).State = EntityState.Modified;
                _context.SaveChanges();
                TempData["Mensaje"] = "Curso actualizado exitosamente";
                return RedirectToAction("Index"); // Redirigir a la página principal de la institución
            }

            return View(institucion);
        }
    }
}

Gabi/InstitutoCurso/ASP .NET MVC/Controllers/UsuariosController.cs
using ASP_.NET_MVC.Data;
using ASP_.NET_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using EntityState = Microsoft.EntityFrameworkCore.EntityState;

namespace ASP_.NET_MVC.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly InstitutoDbContext _context;

        public UsuariosController(InstitutoDbContext context)
        {
            _context = context;
        }

        // Acción para registrar un nuevo usuario
        [HttpGet]
        public ActionResult Registro()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Registro(Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                // Guardar el nuevo usuario en la base de datos
                _context.Usuarios.Add(usuario);
                _context.SaveChanges();
                TempData["Mensaje"] = "Usuario registrado exitosamente";

                // Redirigir a la página de inicio de sesión o a otra vista 
                return RedirectToAction("Registro", "Usuarios");
            }

            return View(usuario);
        }

        // Acción para editar el perfil de usuario
       
        [HttpGet]
        public ActionResult Editar(int id)
        {
            Usuario usuario = _context.Usuarios.Find(id);
            if (usuario == null)
            {
                return RedirectToAction("Error404", "Error");
            }

            return View(usuario);
        }

        [HttpPost]
        public ActionResult Editar(Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                _context.Entry(usuario).State = EntityState.Modified;
                _context.SaveChanges();
                TempData["Mensaje"] = "Usuario editado exitosamente";
                return RedirectToAction("Editar", "Usuarios"); // Redirigir a la página principal
            }

            return View(usuario);
        }
        
        // Otras acciones del controlador para baja de usuario, etc.
    }
}

Gabi/InstitutoCurso/ASP .NET MVC/Views/Cursos/Index.cshtml
@model IEnumerable<ASP_.NET_MVC.Models.Curso>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="RegistroCursos">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaInicio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaFin)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Disponible)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaInicio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaFin)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Disponible)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

Gabi/InstitutoCurso/ASP .NET MVC/Views/Cursos/RegistroCursos.cshtml
@model ASP_.NET_MVC.Models.Curso

@{
    ViewData["Title"] = "RegistroCursos";
}

<h1>RegistroCursos</h1>

<h4>Curso</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="RegistroCursos">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaInicio" class="control-label"></label>
                <input asp-for="FechaInicio" class="form-control" />
                <span asp-validation-for="FechaInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaFin" class="control-label"></label>
                <input asp-for="FechaFin" class="form-control" />
                <span asp-validation-for="FechaFin" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Disponible" /> @Html.DisplayNameFor(model => model.Disponible)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Gabi/InstitutoCurso/ASP .NET MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>    
</div>

Gabi/InstitutoCurso/ASP .NET MVC/Views/Institucion/ActualizarCursos.cshtml
@model ASP_.NET_MVC.Models.Institucion

@{
    ViewData["Title"] = "ActualizarCursos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>ActualizarCursos</h1>

<h4>Institucion</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ActualizarCursos">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Gabi/InstitutoCurso/ASP .NET MVC/Views/Institucion/Index.cshtml
@model ASP_.NET_MVC.Models.Institucion

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<div>
    <h4>Institucion</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Gabi/InstitutoCurso/ASP .NET MVC/Views/Institucion/RegistroInstitucion.cshtml
@model ASP_.NET_MVC.Models.Institucion

@{
    ViewData["Title"] = "RegistroInstitucion";
}

<h1>RegistroInstitucion</h1>

<h4>Institucion</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="RegistroInstitucion">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Gabi/InstitutoCurso/ASP .NET MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASP_.NET_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASP_.NET_MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASP_.NET_MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Registro">Registrate</a> @*Anda*@
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Editar">Editar Usuario</a>@*No funciona todavia*@
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Institucion" asp-action="RegistroInstitucion">Registrar Institucion</a> @*Anda*@
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Institucion" asp-action="Index">Listado Instituciones</a> @*Anda*@
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cursos" asp-action="RegistroCursos">Registrar Curso</a> @*Anda*@
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cursos" asp-action="Index">Listado Cursos</a> @*Anda*@
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ASP_.NET_MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/scripts.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Gabi/InstitutoCurso/ASP .NET MVC/Views/Usuarios/Editar.cshtml
@model ASP_.NET_MVC.Models.Usuario

@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Editar</h1>

<h4>Usuario</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Editar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Gabi/InstitutoCurso/ASP .NET MVC/Views/Usuarios/Registro.cshtml
@model ASP_.NET_MVC.Models.Usuario

@{
    ViewData["Title"] = "Registro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Registro</h1>

<h4>Usuario</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Registro">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}